server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id: 88545216439-9pib5b7nrbt0t87esk0j449dvgmqqrte.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook: # /oauth2/authorization/facebook 이 주소를 동작하게 한다.
            client-id: 354436796502735
            client-secret: 8f2b91ae79126a623f65d40b7395c19f
            scope:
              - email
              - public_profile
          naver:
            client-id: sbZZp6zmxAyCNpgCLgzF
            client-secret: S0WjYX9Y9N
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json의 response 키값으로 리턴해줌.

mybatis:
  type-aliases-package: com.otrodevym.spring
  mapper-locations: mybatis/mapper/**/*.xml
